### ISSUE TITLE
Checkboxes with new collection syntax

### ISSUE THREAD

**Issue by gwincr11** [justinfrench/formtastic#1125]
Hello,

I am working on implementing the new collections version of the checkbox's api. In the past I was using the member label syntax to set the labels for each checkbox like so:

```
<%= f.input :permissions, :as => :check_boxes, member_label: :label_display %>
```

I switched to the new collections syntax. 
```
<%= f.input :permissions, :as => :check_boxes,
 collection: Permission.all.inject([]) { |coll, item| coll.push([item.label_display, item.id]) } %>
```
This syntax was not properly set the checked option on items that have been selected when editing an existing entry.

I also tried switching the to_s on the permissions to see if it would use the to string method for the name. I also tried setting all the label_method options I could find in the base class. This has lead me to needing to use the member_label in order to get the label I want and the properly selected checkboxes. But this has a deprecation warning. 

I am using formtastic in active admin. 

Thanks for the help,
Cory

**Comment by gwincr11** [comment]
This is a has and belongs to many relationship by the way.

**Comment by justinfrench** [comment]
Two things:

1. Can you confirm that nothing else has changed — that your form "works" with the first version and "doesn't work" with the second version (with no other changes to the model or controller?

2. It's fine to keep this code in the view for now (rather than abstracting it to the model), but could you try to match the suggested `:collection` syntax in #1094's second example to rule out an weird stuff with `inject` or your existing syntax? Something like this:

```
<%= f.input :permissions, :as => :check_boxes, :collection => Permission.all.map { |p| [p.label_display, p.id] } %>
```

**Comment by gwincr11** [comment]
I can confirm that with no changes to the model or the controller the version without collection works and the version with collection does not. I can also confirm that changing from inject to map does not effect the result.

**Comment by justinfrench** [comment]
I don't know what to do next on this one, sorry. If you could make a quick, simple sample project that replicates the issue, I'd be more than happy to spin it up and have a play around.

**Comment by dadachi** [comment]
I have same issue. 
Simple HABTM does not work.

**Comment by justinfrench** [comment]
@dadachi @gwincr11 would love to help, can either of you make a quick test-case app for me to bug-fix against?

**Comment by edatrix** [comment]
Hello, I'm seeing the exact same issue with HABTM and ActiveAdmin; checkboxes aren't checked when editing.  Will try to share a test case.

**Comment by tanelj** [comment]
Hi! 

I have same problem with Rails 4.2 and HABTM.

It seems that the problem is that when Array object is passed as `:collection` then `value_method` is detected as `:last`:

https://github.com/justinfrench/formtastic/blob/2f0db5efaea5d8b331a51c31a74e780b9d822857/lib/formtastic/inputs/base/collections.rb#L30

But `value_method` is also used by checkbox `make_selected_values` method. It tries to send this method to object loaded trough HABTM relation (e.g. `permission.send(:last)`) and it gets `nil` since it doesn't respond to method `:last`

https://github.com/justinfrench/formtastic/blob/2f0db5efaea5d8b331a51c31a74e780b9d822857/lib/formtastic/inputs/check_boxes_input.rb#L187

https://github.com/justinfrench/formtastic/blob/2f0db5efaea5d8b331a51c31a74e780b9d822857/lib/formtastic/inputs/base/collections.rb#L141
