### ISSUE TITLE
Problem with color_field form helper 

### ISSUE THREAD

**Issue by andywenk** [justinfrench/formtastic#1143]
Hi,

I saw that you integrated support input[type=color] fields in https://github.com/justinfrench/formtastic/issues/419

I stumbled over this problem:

    [ERROR]: RuntimeError (The :color input requires the color_field form helper, which is only available in Rails 4+):
      /var/www/www.qraex.de/shared/bundle/ruby/2.2.0/gems/formtastic-3.1.3/lib/formtastic/inputs/color_input.rb:34:in `to_html'
      /var/www/www.qraex.de/shared/bundle/ruby/2.2.0/gems/formtastic-3.1.3/lib/formtastic/helpers/input_helper.rb:240:in `input'
      /var/www/www.qraex.de/shared/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/rails/forms.rb:30:in `proxy_call_to_form'
      /var/www/www.qraex.de/shared/bundle/ruby/2.2.0/bundler/gems/activeadmin-95127afc924d/lib/active_admin/views/components/active_admin_form.rb:63:in `input'
      /var/www/www.qraex.de/releases/20150213144943/app/admin/cartridges.rb:44:in `block (3 levels) in <top (required)>'

I have some fields in the database like this:

    f.inputs "Cartridge erstellen" do
    f.input :name
    f.input :qraexid
    f.input :oem
    f.input :capacity
    f.input :q_capacity
    f.input :pages
    f.input :photo_pages
    f.input :bottle
    f.input :cap_sign
    f.input :cap_color
    f.input :cap_color_help
    f.input :mode
    f.input :common_price
    end

The error is pointing to `f.input :cap_color`. Am I required to change the name? As far as I understood the code, it should only be a `type=color` field when writing `f.input :cap_color, as: :color `. Any idea what is wrong here?

Thanks a lot and cheers

Andy

**Comment by justinfrench** [comment]
Hi, I'll take a look at the code later, but the workaround is to specify an explicit `:as => :string` (or similar) to bypass any automatic choices in the code.

**Comment by andywenk** [comment]
Thanks a lot Justin!

**Comment by mikz** [comment]
Right now it chooses :color type when the column contains `color`. https://github.com/justinfrench/formtastic/blob/2f8b987ee4880c4aa06e6ec799eafe48fa46e316/lib/formtastic/helpers/input_helper.rb#L273.
We dropped support for Rails 3. So `color_field` should be available everywhere.

**Comment by justinfrench** [comment]
@andywenk I think I'm going to close this. The problem you had (as I see it) is that you were surprised that a field with a name matching `/color/` used a HTML5 color (a hex code) input instead of a plain text field.

I've though about this for a few minutes and at this stage I've decided not to change anything. Obviously there are many industries where a HTML5 color picker isn't appropriate, but in those cases…

* it is possible to override with `:as => :string`
* it's more likely that the range of colors would come from an ActiveRecord association, so a select box would be more appropriate (and we only default to a color field if there _isn't_ an existing AR association)

I'm going to close this for now, but if anyone still thinks it's a bit too aggressive to default to a color input in these situations, please @ me in a comment.

**Comment by andywenk** [comment]
thanks @justinfrench closing is fine ;-)
