### ISSUE TITLE
Formtastic number only field?

### ISSUE THREAD

**Issue by syndbg** [justinfrench/formtastic#1159]
I have an `input[type=number]` that I want to only accept numbers. Oddly enough, no HTML5 client-side browser validation occurs even though it's type=number.

Is there a way to force re-enable the HTML5 client-side validation?

I've been reading through the docs - https://github.com/justinfrench/formtastic/wiki/3-Formtastic-Inputs and an issue https://github.com/justinfrench/formtastic/issues/662 . It seems like it was disabled on purpose for a good reason at that time. How can I re-enable it for that specific field or globally?

https://github.com/justinfrench/formtastic/wiki/4-formtastic-options is empty and sorry if I'm asking something too obvious.

**Comment by syndbg** [comment]
Ok an initializer in Rails, `config/initializers/formtastic.rb` seems to do the trick.

Still I wonder if I want HTML5 client side validation for that `input[type=number]` field, how can I achieve it?

**Comment by justinfrench** [comment]
If you want pure client-side (browser) validation, yeah, initialisers do it globally. For per-form or per-field, keep in mind that you can add any HTML attributes you like to both the form and the field, so getting a good understanding of the actual attributes you want to see in the rendered HTML will help us guide you to the right Formtastic syntax to achieve it. Closing for now since you seem to have found your way :)
