### ISSUE TITLE
Disabled checkbox hidden field not disabled

### ISSUE THREAD

**Issue by simmerz** [justinfrench/formtastic#498]
The hidden field created alongside a checkbox isn't disabled when the main one is disabled using :disabled => true. This means that rather than no value being submitted for that field, the "negative" value is submitted instead.

**Comment by maxpark-jd** [comment]
Thanks @gabeodess and @justinfrench ! This is a five year old thread but it helped. I checked the documentation first but it led me to use an array of objects rather than an array of ids of the objects. It would be easier to understand if we clarify the document explaining to use an array of ids than objects themselves.

**Comment by justinfrench** [comment]
@maxpark-jd documentation patch welcome!
